# Generated by Django 3.2.25 on 2026-04-20 09:36

from django.db import migrations
import django_tiptap.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=django_tiptap.fields.TipTapTextField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=django_tiptap.fields.TipTapTextField(blank=True, help_text='Short summary shown on the listing page'),
        ),
    ]
