# Generated by Django 3.2.25 on 2025-02-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lyrics', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='MP3File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mp3/')),
                ('voice_part', models.CharField(choices=[('Soprano 1', 'Soprano 1'), ('Soprano 2', 'Soprano 2'), ('Alto 1', 'Alto 1'), ('Alto 2', 'Alto 2'), ('Tenor 1', 'Tenor 1'), ('Tenor 2', 'Tenor 2'), ('Bass 1', 'Bass 1'), ('Bass 2', 'Bass 2'), ('Lead 1', 'Lead 1'), ('Lead 2', 'Lead 2'), ('Other', 'Other')], max_length=50)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp3_files', to='songs.song')),
            ],
        ),
    ]
