# Generated by Django 3.2.25 on 2025-02-18 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('lyrics', models.TextField()),
                ('composer', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SongStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.section')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structure', to='songs.song')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='songs.song'),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='MP3File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='mp3/')),
                ('voice_part', models.CharField(choices=[('Soprano 1', 'Soprano 1'), ('Soprano 2', 'Soprano 2'), ('Alto 1', 'Alto 1'), ('Alto 2', 'Alto 2'), ('Tenor 1', 'Tenor 1'), ('Tenor 2', 'Tenor 2'), ('Bass 1', 'Bass 1'), ('Bass 2', 'Bass 2'), ('Lead 1', 'Lead 1'), ('Lead 2', 'Lead 2'), ('Other', 'Other')], max_length=50)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mp3_files', to='songs.song')),
            ],
        ),
        migrations.CreateModel(
            name='LyricLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.IntegerField()),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lyric_lines', to='songs.section')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_lines', to='songs.song')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ChoirMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], default='member', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LyricTimestamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(blank=True, null=True)),
                ('lyric_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timestamps', to='songs.lyricline')),
                ('mp3_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyric_timestamps', to='songs.mp3file')),
            ],
            options={
                'unique_together': {('lyric_line', 'mp3_file')},
            },
        ),
    ]
