# Generated by Django 3.2.25 on 2025-04-09 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_voicenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicenote',
            name='name',
            field=models.CharField(default='None', max_length=255, unique=True),
        ),
    ]
