# Generated by Django 3.2.25 on 2025-02-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_choirmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='composer',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
