# Generated by Django 3.2.25 on 2025-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_section_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricline',
            name='voice_part',
            field=models.CharField(blank=True, choices=[('soprano', 'Soprano'), ('alto', 'Alto'), ('tenor', 'Tenor'), ('bass', 'Bass')], max_length=10, null=True),
        ),
    ]
