# Generated by Django 3.2.25 on 2025-04-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20250409_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voicenote',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
