# Generated by Django 3.2.25 on 2025-02-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20250218_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='slogan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='youtube_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
