# Generated by Django 3.2.25 on 2025-04-11 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_voicenote_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyricline',
            name='instruction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mp3file',
            name='voice_part',
            field=models.CharField(choices=[('Soprano 1', 'Soprano 1'), ('Soprano 2', 'Soprano 2'), ('Alto 1', 'Alto 1'), ('Alto 2', 'Alto 2'), ('Tenor 1', 'Tenor 1'), ('Tenor 2', 'Tenor 2'), ('Bass 1', 'Bass 1'), ('Bass 2', 'Bass 2'), ('Lead 1', 'Lead 1'), ('Lead 2', 'Lead 2'), ('Other', 'Other')], max_length=200),
        ),
        migrations.AlterField(
            model_name='section',
            name='instruction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='voicenote',
            name='voice_part',
            field=models.CharField(choices=[('Soprano', 'Soprano'), ('Alto', 'Alto'), ('Tenor', 'Tenor'), ('Bass', 'Bass'), ('Other', 'Other')], max_length=200),
        ),
    ]
