# Generated by Django 3.2.25 on 2025-02-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20250225_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyricline',
            name='instruction',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
