# Generated by Django 3.2.25 on 2025-02-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_section_instruction'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
