# Generated by Django 3.2.25 on 2025-02-25 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_alter_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='slogan',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
