# Generated by Django 3.2.25 on 2026-04-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_auto_20260420_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='composition_type',
            field=models.CharField(blank=True, choices=[('original', 'Original'), ('arranged', 'Arranged'), ('transcribed', 'Transcribed')], default='original', max_length=20),
        ),
    ]
