# Generated by Django 3.2.25 on 2026-04-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_song_composition_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongComposerContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition_type', models.CharField(choices=[('original', 'Original'), ('arranged', 'Arranged'), ('transcribed', 'Transcribed')], default='original', max_length=20)),
                ('position', models.PositiveIntegerField(default=1)),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_links', to='songs.composer')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composer_links', to='songs.song')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('song', 'composer')},
            },
        ),
        migrations.AddField(
            model_name='song',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='composed_songs', through='songs.SongComposerContribution', to='songs.Composer'),
        ),
    ]
