# Generated by Django 3.2.25 on 2026-04-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_backfill_song_composer_contributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='composer',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL suggested by AI'),
        ),
    ]
